http:
  serversTransports:
    mytransport:
      insecureSkipVerify: true

  # Put my proxmox instance behind traefikv2 (This is mostly so they can have a domainname)
  routers:
    proxmox:
      entryPoints:
      - https
      rule: "Host(`proxmox.example.com`)"
      service: proxmox

  services:
    proxmox:
      loadBalancer:
        serversTransport: mytransport
        servers:
        - url: "https://192.168.1.10:8006"


  # Authelia Middleware
  middlewares:
    forward-auth:

      forwardAuth:
        address: "http://authelia:9091/api/verify?rd=https://authelia.example.com"
        trustForwardHeader: true
        authResponseHeaders:
          - "Remote-User"
          - "Remote-Groups"
