version: "3.8"

services:
  traefik:
    image: traefik:latest
#    image: traefik:chevrotin
    ports:
      - "80:80"
      - "8080:8080" # traefik dashboard
      - "443:443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/data/config/traefikv2:/etc/traefik
    networks:
      - traefik_public
    deploy:
      placement:
        constraints: [node.role == manager]
      labels:
        - "traefik.docker.network=traefik_public"
        - "traefik.http.routers.api.rule=HostHeader(`traefik.example.co.nz`)"
        - "traefik.http.routers.api.service=api@internal"
        - "traefik.http.services.api.loadbalancer.server.port=8080"
        - "traefik.http.routers.api.middlewares=forward-auth@file"


 # Cloudflare DDNS - Dynamic DNS Updater
  cf-ddns:
    container_name: cf-ddns
    image: oznu/cloudflare-ddns:latest
    restart: always
    environment:
      - API_KEY=API
      - ZONE=example.co.nz
      - PROXIED=true
      - SUBDOMAIN=traefik
      - RRTYPE=A
      - DELETE_ON_STOP=false
      - DNS_SERVER=1.1.1.1

networks:
  traefik_public:
    external: true
