version: "3.4"

services:
  bitwarden:
    image: bitwardenrs/server
    env_file: /var/data/config/bitwarden/bitwarden.env
    volumes:
      - /var/data/bitwarden:/data/:rw
    networks:
        - traefik_public
    deploy:
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.bitwarden.rule=Host(`bitwarden.example.co.nz`)"
        - "traefik.http.services.bitwarden.loadbalancer.server.port=80"
        - "traefik.http.routers.bitwarden.service=bitwarden"
        - "traefik.http.routers.bitwarden-websocket.rule=Host(`bitwarden.example.co.nz`) && Path(`/notifications/hub`)"
        - "traefik.http.routers.bitwarden-websocket.service=bitwarden-websocket"
        - "traefik.http.services.bitwarden-websocket.loadbalancer.server.port=3012"

networks:
  traefik_public:
    external: true
