version: "3"
services:
  duplicati:
    image: linuxserver/duplicati
    env_file: /var/data/config/backup/backup.env
    deploy:
      replicas: 1
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.backup.rule=Host(`backup.example.co.nz`)"
        - "traefik.http.services.backup.loadbalancer.server.port=8200"
        - "traefik.http.routers.backup.entrypoints=https"
        - "traefik.http.routers.backup.middlewares=forward-auth@file"
    volumes:
      - /var/data/config/backup:/config
      - /var/data:/source
    ports:
      - 8200:8200
    networks:
      - traefik_public
      - internal

networks:
  traefik_public:
    external: true
  internal:
    driver: overlay
    ipam:
      config:
        - subnet: 172.16.55.0/24
