version: "3.4"

services:
  authelia:
    image: authelia/authelia:4.21.0
    volumes:
      - /var/data/config/authelia:/config
    networks:
      - traefik_public
    deploy:
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.authelia.entrypoints=https"
        - "traefik.http.routers.authelia.rule=Host(`authelia.example.co.nz`)"
        - "traefik.http.middlewares.authelia.forwardauth.address=http://authelia:9091/api/verify?rd=https://authelia.example.co.nz"
        - "traefik.http.middlewares.authelia.forwardauth.trustForwardHeader=true"
        - "traefik.http.middlewares.authelia.forwardauth.authResponseHeaders=Remote-User, Remote-Groups"
        - "traefik.http.services.authelia.loadbalancer.server.port=9091"


networks:
  traefik_public:
    external: true
