###############################################################
#                   Authelia configuration                    #
###############################################################

host: 0.0.0.0
port: 9091
log_level: warn

jwt_secret: secret
default_redirection_url: https://authelia.example.co.nz

totp:
  issuer: authelia.com
  period: 30
  skew: 1


authentication_backend:
  file:
    path: /config/users_database.yml
    password:
      algorithm: sha512
      iterations: 50000
      key_length: 32
      salt_length: 32


access_control:
  default_policy: one_factor
  rules:
    - domain: "*.example.co.nz"
      policy: one_factor


session:
  name: authelia_session
  # This secret can also be set using the env variables AUTHELIA_SESSION_SECRET_FILE
  secret: secret
  expiration: 3600 # 1 hour
  inactivity: 300 # 5 minutes
  domain: example.co.nz # Should match whatever your root protected domain is

regulation:
  max_retries: 3
  find_time: 120
  ban_time: 300

notifier:
  filesystem:
    filename: /config/notification.txt


storage:
  local:
    path: /config/db.sqlite3
