version: '3'
services:
  rss:
    image: rssbridge/rss-bridge:latest
    volumes:
      - /var/data/config/rss:/config
    networks:
      - traefik_public
    deploy:
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.rss.rule=Host(`rss.example.co.nz`)"
        - "traefik.http.services.rss.loadbalancer.server.port=80"

networks:
  traefik_public:
    external: true