version: '3.4'

services:
    archivebox:
        image: archivebox/archivebox
        env_file: /var/data/config/archivebox/archivebox.env
        command: server --quick-init 0.0.0.0:8000
        networks:
          - traefik_public
        deploy:
          labels:
            - "traefik.enable=true"
            - "traefik.http.routers.archive.rule=Host(`archive.example.co.nz`)"
            - "traefik.http.services.archive.loadbalancer.server.port=8000"
            - "traefik.http.routers.archive.entrypoints=https"
        volumes:
          - /var/data/archivebox:/data


networks:
  traefik_public:
    external: true
